Imports MySql.Data.MySqlClient ' this is to import MySQL.NET
Imports System
Imports System.Text.RegularExpressions

Public Class frmPurchaseOrderList
    Protected Overrides Function ProcessCmdKey(ByRef msg As Message, ByVal keyData As Keys) As Boolean
        If keyData = (Keys.Escape) Then
            Me.Close()
        End If
        Return ProcessCmdKey
    End Function

    Private Sub frmForApprovalList_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.Icon = ico
        FilterSelectedTab()
    End Sub

    Private Sub TabControl1_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles TabControl1.SelectedIndexChanged
        FilterSelectedTab()
    End Sub

    Public Function FilterSelectedTab()
        If TabControl1.SelectedTab Is tabForApproval Then
            MyDataGridView.Parent = tabForApproval
            ShowByPurchaseOrder(txtfilter.Text, " verified=0 and forpo=1 and tblpurchaseorder.cancelled=0 and officeid='" & compOfficeid & "' ", "forapproval")
            MyDataGridView.ContextMenuStrip = Nothing
        ElseIf TabControl1.SelectedTab Is tabApproved Then
            MyDataGridView.Parent = tabApproved
            ShowByPurchaseOrder(txtfilter.Text, " verified=1 and forpo=1 and tblpurchaseorder.cancelled=0 and delivered=0 and officeid='" & compOfficeid & "' ", "approved")
            MyDataGridView.ContextMenuStrip = Nothing
        ElseIf TabControl1.SelectedTab Is tabCancelled Then
            MyDataGridView.Parent = tabCancelled
            ShowByPurchaseOrder(txtfilter.Text, " forpo=1 and tblpurchaseorder.cancelled=1 and officeid='" & compOfficeid & "' ", "cancelled")
            MyDataGridView.ContextMenuStrip = Nothing
        ElseIf TabControl1.SelectedTab Is tabDelivered Then
            MyDataGridView.Parent = tabDelivered
            ShowByPurchaseOrder(txtfilter.Text, " verified=1 and forpo=1 and tblpurchaseorder.cancelled=0 and delivered=1 and paymentupdated=0 and officeid='" & compOfficeid & "' ", "delivered")
            MyDataGridView.ContextMenuStrip = cms_em
        ElseIf TabControl1.SelectedTab Is tabClosed Then
            MyDataGridView.Parent = tabClosed
            ShowByPurchaseOrder(txtfilter.Text, " verified=1 and forpo=1 and tblpurchaseorder.cancelled=0 and delivered=1 and paymentupdated=1 and officeid='" & compOfficeid & "' ", "delivered")
            MyDataGridView.ContextMenuStrip = Nothing
        End If
    End Function
    Private Sub txtfilter_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtfilter.KeyPress
        If e.KeyChar() = Chr(13) Then
            While MainForm.BackgroundWorker1.IsBusy()
                Application.DoEvents()
            End While
            FilterSelectedTab()
        End If
    End Sub


#Region "PURCHASE ORDER"
    Public Sub ShowByPurchaseOrder(ByVal SearchKey As String, ByVal filter As String, ByVal filterby As String)
        MyDataGridView.DataSource = Nothing : dst = New DataSet
        Dim strFilterby As String = ""
        If filterby = "forapproval" Then
            strFilterby = " date_format(datetrn,'%Y-%m-%d %r') as 'Date Generated' "

        ElseIf filterby = "approved" Then
            strFilterby = " date_format(dateverified,'%Y-%m-%d %r') as 'Date Approved' "

        ElseIf filterby = "cancelled" Then
            strFilterby = " date_format(datecancelled,'%Y-%m-%d %r') as 'Date Cancelled' "

        ElseIf filterby = "delivered" Then
            strFilterby = " date_format(datedelivered,'%Y-%m-%d %r') as 'Date Delivered' "

        End If
        msda = New MySqlDataAdapter("Select requestref,tblpurchaseorder.vendorid, ponumber as 'PO Number', " _
                   + " (select ucase(companyname) from tblglobalvendor where vendorid = tblpurchaseorder.vendorid) as 'Supplier', " _
                   + " invoiceno as 'Invoice No.', subtotal as 'Sub Total',Vat,  charges as 'Charges',discount as 'Discount',totalamount as 'Total', " _
                   + " (select fullname from tblaccounts where accountid = tblpurchaseorder.createby) as 'Generated By', " _
                   + " case when (verified=1 and forwarded=0 and delivered=0) then 'Waiting to be forwarded'  when (verified=1 and forwarded=1 and delivered=0) then 'Purchase Order Available' else ifnull((select if(count(*)>0,cast(concat(count(*), ' File(s) Attached') as char),null) from "  & sqlfiledir & ".tblattachmentlogs where refnumber = tblpurchaseorder.ponumber or refnumber=tblpurchaseorder.requestref),'-') end as 'Attachment',  " _
                   + strFilterby _
                   + " from tblpurchaseorder " _
                   + " where  " & filter _
                   + " and  (ponumber like '%" & SearchKey & "%' or " _
                   + " (select sum(total) from tblrequisitionsitem where ponumber=tblpurchaseorder.ponumber and vendorid =  tblpurchaseorder.vendorid) like '%" & SearchKey & "%' or " _
                   + " date_format(tblpurchaseorder.datetrn,'%Y-%m-%d') like '%" & SearchKey & "%' or " _
                   + " (select ucase(companyname) from tblglobalvendor where vendorid = tblpurchaseorder.vendorid) like '%" & SearchKey & "%' or " _
                   + " date_format(datetrn,'%Y-%m-%d') like '%" & SearchKey & "%') order by datetrn desc", conn)

        msda.Fill(dst, 0)
        MyDataGridView.DataSource = dst.Tables(0)
        GridHideColumn(MyDataGridView, {"requestref", "vendorid"})
        GridColumnAlignment(MyDataGridView, {"PO Number", "Invoice No.", "Attachment"}, DataGridViewContentAlignment.MiddleCenter)
        If filterby = "forapproval" Then
            GridColumnAlignment(MyDataGridView, {"Date Generated"}, DataGridViewContentAlignment.MiddleCenter)
        ElseIf filterby = "approved" Then
            GridColumnAlignment(MyDataGridView, {"Date Approved"}, DataGridViewContentAlignment.MiddleCenter)
        ElseIf filterby = "cancelled" Then
            GridColumnAlignment(MyDataGridView, {"Date Cancelled"}, DataGridViewContentAlignment.MiddleCenter)
        ElseIf filterby = "delivered" Then
            GridColumnAlignment(MyDataGridView, {"Date Delivered"}, DataGridViewContentAlignment.MiddleCenter)
        End If
        GridCurrencyColumn(MyDataGridView, {"Sub Total", "Vat", "Charges", "Discount", "Total"})
        GridColumnAlignment(MyDataGridView, {"Sub Total", "Vat", "Charges", "Discount", "Total"}, DataGridViewContentAlignment.MiddleRight)
    End Sub

    Private Sub MyDataGridView_CellDoubleClick(sender As Object, e As DataGridViewCellEventArgs) Handles MyDataGridView.CellDoubleClick
        If MyDataGridView.Item("PO Number", MyDataGridView.CurrentRow.Index).Value().ToString() = "" Then Exit Sub
        frmPurchaseOrderView.Text = "Purchase Order Status"
        frmPurchaseOrderView.ponumber.Text = MyDataGridView.Item("PO Number", MyDataGridView.CurrentRow.Index).Value().ToString()
        If frmPurchaseOrderView.Visible = True Then
            frmPurchaseOrderView.Focus()
        Else
            frmPurchaseOrderView.Show(Me)
        End If
    End Sub
#End Region

    Private Sub cmdLocalData_Click(sender As Object, e As EventArgs) Handles cmdLocalData.Click
        FilterSelectedTab()
    End Sub

  
End Class